/**
 * This is an autogenerated netlist code from CircuitVerse. Verilog Code can be
 * tested on https://www.edaplayground.com/ using Icarus Verilog 0.9.7. This is an
 * experimental module and some manual changes make need to be done in order for
 * this to work.
 *
 * If you have any ideas/suggestions or bug fixes, raise an issue
 * on https://github.com/CircuitVerse/CircuitVerse/issues/new/choose
 */

module bus_transciever(inout_1, inout_2, dir);
  inout inout_1;
  inout inout_2; 
  input dir;
  wire not_0_out, TriState_1_out, TriState_0_out;
  assign not_0_out = ~dir;
  assign TriState_1_out = (not_0_out!=0) ? TriState_0_out : 1'b?;
  assign inout_1 = TriState_1_out;
  assign TriState_0_out = (dir!=0) ? TriState_1_out : 1'b?;
endmodule